### ISSUE TITLE
Please remove my official email id 'shiv_kumar10@infosys.com' from your page

### ISSUE THREAD

**Issue by shivonkar** [RosePasta/Denchmark_BRs#1]
Hi,
Please remove my official email id 'shiv_kumar10@infosys.com' from your page

https://github.com/RosePasta/Denchmark_BRs/blob/main/Generator/data/stage2_bugreports/apache+incubator-mxnet/8575.xml

**Comment by RosePasta** [comment]
Hello. I removed your email from the mentioned page.
If you need other changes, please notify us.
